[package]
name = "robocopy"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rust 重写的 Windows robocopy.exe（跨平台整活）"

[[bin]]
name = "robocopy"
path = "src/main.rs"

[dependencies]
windowshit-args = { path = "../args" }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_System_SystemInformation", "Win32_Storage_FileSystem", "Win32_Foundation"] }
