[package]
name = "getmac"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rust 重写的 Windows getmac.exe（跨平台整活）"

[[bin]]
name = "getmac"
path = "src/main.rs"

[dependencies]
windowshit-args = { path = "../args" }
windowshit-i18n = { path = "../i18n" }

[target.'cfg(windows)'.dependencies]
ipconfig = "0.3"
windows-sys = { version = "0.52", features = ["Win32_System_Console", "Win32_Foundation", "Win32_System_Registry"] }

[target.'cfg(not(windows))'.dependencies]
netdev = { version = "0.46", features = ["gateway"] }
