[package]
name = "windowshit-netinfo"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Windowshit 公共网络适配器数据层（跨平台统一）"

[dependencies]

[target.'cfg(windows)'.dependencies]
ipconfig = "0.3"

[target.'cfg(not(windows))'.dependencies]
netdev = { version = "0.46", features = ["gateway"] }
