[package]
name = "windowshit-winreg"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Windowshit 公共注册表读取层（Windows 读注册表；非 Windows 参考 regedit 读 /etc、~/.config、/boot 配置文件夹）"

[dependencies]

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_System_Registry", "Win32_Foundation"] }
