[package]
name = "systeminfo"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Rust 重写的 Windows systeminfo.exe（跨平台整活）"

[[bin]]
name = "systeminfo"
path = "src/main.rs"

[dependencies]
windowshit-i18n = { path = "../i18n" }
windowshit-netinfo = { path = "../netinfo" }
windowshit-winreg = { path = "../winreg" }
sysinfo = "0.39"
os_info = { version = "3.15", default-features = false }
hostname_rs = { package = "hostname", version = "0.4" }
chrono = "0.4"
